### ISSUE TITLE
Password protected embedded dashboard is no longer working

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#1126]
Got a report that a password protected embedded dashboard within WP plugin is no longer working. Tested the password embed directly on my site without a WP plugin and got the same error. Embed without PW works fine both in browser and within the WP plugin.

In Firefox:

![Screenshot from 2021-06-14 09-52-40](https://user-images.githubusercontent.com/34340819/121858177-a0661d80-ccf6-11eb-9e6d-9fa54c19c435.png)

In Chromium:

![Screenshot from 2021-06-14 09-53-00](https://user-images.githubusercontent.com/34340819/121858197-a65bfe80-ccf6-11eb-8428-5a948122df73.png)

**Comment by ukutaht** [comment]
This is intended because we cannot guarantee the security of the password when it's embedded on another domain. See discussion here: https://github.com/plausible/analytics/issues/919#issuecomment-831268574. 

Sorry I just made the decision without communicating it. Is there a good place to make a note in the docs or the WP plugin?

**Comment by metmarkosaric** [comment]
np! i'll update the docs/blog post to mention this
