### ISSUE TITLE
Getting 400 status code in response from Events API

### ISSUE THREAD

**Issue by markcellus** [plausible/analytics#1309]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

I'm attempting to make a curl request to test using the [Events API](https://plausible.io/docs/events-api) and getting 400 error status code from response. I may be using the endpoint incorrectly, but here's what I'm trying (taken from the Events API page).

_Note: `<redacted>` is just my domain name associated with my Plausible account._

```
curl -X POST https://plausible.io/api/event -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.284' -H 'X-Forwarded-For: 127.0.0.1' -H 'accept: */*' --data-binary '{"name":"pageview","url":"http://<redacted>","domain":"<redacted>","width":1666}'
```

### Expected behavior

A 200 response

### Environment

```markdown
- OS: Ubuntu 21.04
- Browser: N/A
- Browser Version: N/A
```

**Comment by ukutaht** [comment]
Hey,

Sorry, this is a mistake with the `curl` command. I left out a header, if you add `Content-Type: application/json` then it should work OK. I've adjusted the documentation accordingly: https://plausible.io/docs/events-api. A succesful request gives a 202 response.

**Comment by markcellus** [comment]
Works great now, thanks! :+1:

**Comment by andyj2022** [comment]
The curl sample in https://plausible.io/docs/events-api also returns 400 status code.

`curl -i -X POST https://plausible.io/api/event -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.284' -H 'X-Forwarded-For: 127.0.0.1' -H 'Content-Type: application/json' --data '{"name":"pageview","url":"https://plausible.io","domain":"plausible.io","screen_width":1666}'`

Returns a CORS error, and it seems to be produced because "access-control-allow-headers" from "plausible.io" does not allow sending "X-Forwarded-For":

`access-control-allow-headers: Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since,X-CSRF-Token`
