### ISSUE TITLE
macOS 11 misidentified as 10.15 in OS version list

### ISSUE THREAD

**Issue by jasongrlicky** [plausible/analytics#1377]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When I visit my site using Safari 15.0 on a computer running macOS 11.6, it is noted in the plausible dashboard as being macOS 10.15. I discovered this because I was noticing that there were almost no users showing up in my analytics on macOS 11, which was suspicious because it has been out for a year now.

### Expected behavior

macOS 11 visitors should be reported as macOS 11. Thank you so much!

### Environment

```markdown
- OS: macOS 11.6
- Browser: Safari
- Browser Version: 15.0
```

**Comment by metmarkosaric** [comment]
thanks for reporting @jasongrlicky! this is caused because Safari on Mac intentionally hides the Big Sur version number: https://bugs.webkit.org/show_bug.cgi?id=216593. this affects Plausible, Google Analytics and any other analytics tool. there's not much we can do about it. see also https://github.com/plausible/analytics/discussions/1263
