### ISSUE TITLE
Hardcoded docker user causes problems

### ISSUE THREAD

**Issue by viraptor** [plausible/analytics#1404]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When running the docker image, the user is hardcoded to uid 1000 and the files are owned by that user.
This has some issues:
- it most likely collides with the first user of the host, which is a potential security problem
- files being deployed as executable specifically for that user cannot be run by others (resulting in 0744 `/app/.../elixir` not being runnable with a different uid)
- some files like `/app/lib/tzdata-1.0.5/priv/latest_remote_poll.txt` are expected to be written to, but that breaks with other uids

### Expected behavior

Be able to run the official docker container with uid different than 1000

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by ukutaht** [comment]
Agree that this should be fixed. More reading: https://sysdig.com/blog/dockerfile-best-practices/#1

**Comment by djanda97** [comment]
Should the UID be hardcoded to a different value other than 1000 or dynamic assigned at runtime?

**Comment by viraptor** [comment]
Ideally, it should be possible to use any uid people want.

**Comment by ruslandoga** [comment]
[Here's](https://gist.github.com/ruslandoga/289e6b73381c4fdad404dc28f8f46dd0) the Dockerfile that `mix phx.gen.release --docker` generates. I wonder if we could use something similar for the user setup.

**Comment by ruslandoga** [comment]
👋 @viraptor  Sorry for taking too long to get back.

I would like to clarify a few points. 

For the first issue, even if the UID matches, the container's process is isolated with different access rights from a host process with UID 1000. And Plausible doesn't write to mounted volumes so that mitigates potential conflicts with host user's UID on written files.

Regarding the executables, I'm trying to understand the scenario where a user other than `plausibleuser` would need to run them inside the container. Could you elaborate?

Lastly, files like `/app/lib/tzdata-1.0.5/priv/latest_remote_poll.txt` are exclusively used by Plausible. Can you explain the issue that arises with other UIDs?

A bit more detail on these points would be helpful to address your concerns effectively. Thanks!

**Comment by ruslandoga** [comment]
> Ideally, it should be possible to use any uid people want.

This would require modifying `entrypoint.sh` to create a user and change ownership of all relevant files to it. While doable, I think it would complicate the setup and introduce more room for errors.

**Comment by ruslandoga** [comment]
Maybe we can do it like [in ClickHouse:](https://github.com/ClickHouse/ClickHouse/blob/701e2fb6e350a6f84c0826b8abec419316cd664d/docker/server/Dockerfile.alpine#L39-L72) fixed uid but some directories writable / executable by all.

**Comment by viraptor** [comment]
Unfortunately I moved to another project instead, so can't really provide more info here, sorry.

**Comment by ruslandoga** [comment]
@viraptor Thank you nonetheless!

Just in case, https://github.com/plausible/analytics/pull/2986 probably resolves the issues you were having as with these changes `plausible/analytics` container can run as any `uid:gid`.
