### ISSUE TITLE
Direct/None missing in Top Sources overview

### ISSUE THREAD

**Issue by stnwk** [plausible/analytics#1602]
Hi :)

I'm using the paid version and I noticed on the dashboard Direct/None is missing in Top Sources and only shows when I open the details.

Is this a bug? Why would it be desired behaviour?

Thanks!

**Comment by metmarkosaric** [comment]
thanks for reporting! this is intentional and there's no plan to change it. when we were building this we were testing both versions (direct in default list and the current way). turns out most sites have a lot of direct traffic and the community didn't find the "direct/none" number actionable plus it skewed the comparison we do in the default view so we left it out in the "details" only. there's a thread here: https://github.com/plausible/analytics/discussions/1539

**Comment by stnwk** [comment]
Thanks for the super fast reply!

**Comment by metmarkosaric** [comment]
you're welcome!
