### ISSUE TITLE
Spam from advertisefr*e.co.uk

### ISSUE THREAD

**Issue by nicbou** [plausible/analytics#1619]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Since a few days, I see around 90 visitors a day from "advertisefree.co.uk". This is clearly fake traffic. Their website sells traffic to your website or something like that.

### Expected behavior

This fake traffic should be filtered out

### Screenshots

<img width="822" alt="Screenshot 2022-01-19 at 17 28 43" src="https://user-images.githubusercontent.com/88917/150173481-a485afb9-9f81-49cf-9054-79ce3dd55033.png">

**Comment by ukutaht** [comment]
Thanks @nicbou!

The plan is to integrate [this list](https://github.com/matomo-org/referrer-spam-list/blob/master/spammers.txt) of referrer spammers and to ignore their traffic at all times. This isn't implemented yet but that's the idea.

**Comment by paskal** [comment]
My two cents: that particular domain is not in the list, so it would be helpful to have the ability to have customizable list of domains with default or suggestion of the list you linked.

**Comment by ukutaht** [comment]
Yeah, wouldn't hurt to be able to customize it per installation. Although if it's really referrer spam then I would also try to get the reported domain on that list.

**Comment by paskal** [comment]
Sure, however, "convince third-party GitHub repo owner to merge your PR" doesn't look like the simplest strategy to remove referrer you don't like from the stats. Especially given that people use the internet in hundreds of languages. While that list would be helpful for someone in the US or Europe with English-speaking auditory, there are zero domains mentioned in `.cn` and `.tl` and many other domain zones currently.
Also, I would strongly prefer my per-case investigation for my website rather than trusting that third-party repository on altering the stats.

Another point you already most likely have in mind, but I think worth pointing out aloud, is that I think that system should filter the rendered data without altering the underlying data. Otherwise, it won't be possible to recover from wrongfully added entry.
Also, it might be helpful to give the plausible administrator ability to see traffic including the filtered one, and\or only filtered traffic to verify if the filter is doing a decent job for that particular domain, and to be able to troubleshoot the situation when someone, for example, putting too much traffic on you, which you might observe as site slowness for all visitors.

---

It's not my first comment here, but thanks to everyone involved in Plausible development, it's a delight to use it, especially as a free self-hosted solution with well-written documentation. I learned about it from [Gergely Orosz](https://blog.pragmaticengineer.com/stats/), and I hope Plausible got the exposure it deserved from his recommendations.

**Comment by ukutaht** [comment]
Thanks @paskal !

Maybe there's a way to use some filtering primitives to achieve the same thing. One thing I've wanted to add is a way to save filters in the UI and then to mark a certain saved filter as your default. So in theory you could have a saved filter a rule like:
* Referrer NOT IN (spammer1.com, spammer2.com)

Then save that as your default filter. We'd need to build a NOT IN filter type and saved filters for it but it could work.

> I think that system should filter the rendered data without altering the underlying data.

This would be true for the filter approach mentioned above. However, my plan with Matomo's referrer-spam-list is to truly filter out those requests at the earliest point in our ingestion pipeline. We've decided to actually filter out all unwanted traffic in our hosted service (this includes non-human User-Agents and IP addresses of known proxies/datacenters).

Storage costs are a real thing for us and so far there has been one request from thousands of customers to see bot traffic on their dashboard. We don't see it as a worthwhile use of disk space. YMMV and self-hosters are free to run Plausible as they see fit. If need be, we can offer a config option to soft-delete unwanted traffic somehow.

**Comment by metmarkosaric** [comment]
hi @nicbou! we have now integrated Plausible with [this referrer spam list](https://github.com/matomo-org/referrer-spam-list/blob/master/spammers.txt) and we'll start automatically removing any of this traffic on the next deploy of Plausible. You can see the [merged PR here](https://github.com/plausible/analytics/pull/1750).

I've also submitted advertisefree.co.uk domain to be added to the list and you can see the [PR for that here](https://github.com/matomo-org/referrer-spam-list/pull/1315).

closing this for now. if you do find more spam domains in your Plausible dashboard sources please do either report it to us so we can submit it to the referrer spam list ourselves or feel free to submit it directly too as we'll keep our list in sync with theirs. thanks!

**Comment by nicbou** [comment]
Thank you! I can't overstate how happy I am with Plausible

**Comment by metmarkosaric** [comment]
thanks for the kind words, appreciate that!
