### ISSUE TITLE
Separate billing email address?

### ISSUE THREAD

**Issue by tomchadwin** [plausible/analytics#1705]
We've just subscribed, and really need service and tech emails to go to a different email address from invoices. Is that on your roadmap? Many thanks.

**Comment by metmarkosaric** [comment]
thanks @tomchadwin! it's unfortunately not possible to change an email address or set an email for invoices in Paddle API (our payment processor). this is what they told us couple of weeks ago:

"Regarding an API to change email addresses, unfortunately we do not have an API enabling you to do so as email change requests are not process automatically, and require a member of our Buyer Support team to do so manually. This is because a buyer's email address can be linked to various orders across our platform (i.e., linked to another seller's orders) and so we need to confirm with the buyer that they own those other orders. However we are currently working on enabling buyers and sellers to manage email addresses more effectively, so the current logic will not be the case by the end of the year."

i'm closing this issue as we keep issues to actual bugs only and there's a thread on this feature request already at https://github.com/plausible/analytics/discussions/726

**Comment by tomchadwin** [comment]
Thanks, and apologies for missing that issue. Have upvoted it.

**Comment by metmarkosaric** [comment]
np, thanks!
