### ISSUE TITLE
Please use complete URL for stats

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#177]
"My Blogsoftware uses the part after the question mark to differentiate the different blog articles.

Example: https://www.deimeke.net/dirk/blog/index.php?/archives/4015-Lesen!.html

The stats only show “/dirk/blog/index.php”, which lacks the important information."

([imported from the old roadmap](https://plausible.nolt.io/149))

**Comment by ddeimeke** [comment]
I will be happy to try plausible again once this feature is implemented.

**Comment by tckb** [comment]
@ddeimeke the example that you've shared _does not_ conform to [standard URI scheme ](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Generic_syntax) for identifying resources. 

A standard syntax is of the following format: 
```
scheme:[//authority]path[?query][#fragment]
```
the important information you seek is in the "query" part of the URL and the tracking is possible for different paths which does not include queries.

**Comment by ddeimeke** [comment]
@tckb It depends on your point of view.

You query the blog for the article called "/archives/4015-Lesen!.html".

I understand, that it is not possible (yet), but nevertheless it is how my Blogsoftware delivers the articles. If plausible.io does not recognize this, it is the wrong software for me.

**Comment by ukutaht** [comment]
By default we strip all query parameters except attribution related ones (`ref`, `utm_source`, etc.). I did it this way because:
* Query params often contain personal or sensitive data
* Query params are rarely used to distinguish different pages (as your blog software does)

I would like to keep stripping query params by default but we should probably allow a configurable whitelist so people can choose which query params to send to the server.

**Comment by onesork** [comment]
Hi @ukutaht, 

I run into issues due to this limitation as well.

> Query params often contain personal or sensitive data

I don't think that's frequent. Google Analytics has a policy that says you cannot store Personally Identifiable Information (PII) anywhere within GA (incl. URLs). Yet, you rarely need to make any adjustments to comply with this policy.

Of course, it depends on your definition of sensitive data. Most common would probably be queries from an internal search that are frequently stored in the URL. Are these considered sensitive as well?

> Query params are rarely used to distinguish different pages (as your blog software does)

I'm afraid that's unfortunately not on par with everyday reality. Many websites use parameters for filters/labels/categories that you want to be able to track. Others use that to communicate some form of state that's handy for conversion tracking.

For example, Ghost's default conversion goal destination is /?action=subscribe&success=true - which I'm not able to track easily (to give one example).

But I guess the whitelisting would solve most of these issues.

Thanks!

Best,

Jan

**Comment by websocket98765** [comment]
Or instead of a whitelist, maybe offer a setting to enable or disable query string tracking for all or some URLs, and allow some URLs to be deleted directly from analytics in case PII gets through. It sounds like a headache to maintain a whitelist for all routes on my site, but maybe it'd be ok.
