### ISSUE TITLE
beam.smb memory usage

### ISSUE THREAD

**Issue by emhl** [plausible/analytics#1802]
the most resource intensive part of plausible is a process called beam.smb that is using 200Mb of memory conistently. twice the amount that clickhouse-serv is using.
from what i've heard that programm is probably part of couchdb which is used for caching. is there a way to limit or disable said caching to limit the resource usage when idle?
```shell
/app/erts-12.0/bin/beam.smp -- -root /app -progname erl -- -home /app -- -noshell -s elixir start_cli -mode embedded -setcookie S4WHAF4LH5WHSPWUHPKIVMSFISQKQJVFWEGHSP7YW6MT5LKCNDCA==== -sname plausible -config /app/releases/0.0.1/sys -boot /app/releases/0.0.1/start -boot_var RELEASE_LIB /app/lib -- -extra --no-halt
```

**Comment by ukutaht** [comment]
Plausible is an Elixir service. Elixir compiles to BEAM bytecode and runs on the BEAM virtual machine. What you're seeing is the main web server process that handles all data ingestion as well as serving the dashboard. It keeps in memory things like IP geolocation database, User-Agent database, Referrer database, Referrer blocklist, ISO3166 country and region names as well as Geonames city names. These are all necessary to make sure the app is responsive and fast, so it doesn't have to go to disk to look up IP-to-City data for example.

Sorry, there are no plans to address this memory usage. Web analytics is fairly memory-intense because it must be able to handle a lot of data fast and it cannot afford to touch disk for these operations.
