### ISSUE TITLE
Email source icon is broken

### ISSUE THREAD

**Issue by taylorlapeyre** [plausible/analytics#1842]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

The email source icon is broken, and doesn't render with an actual image. The image URL appears to be "https://plausible.io/favicon/sources/email"

### Expected behavior

The icon should render properly.

### Screenshots

<img width="325" alt="Screen Shot 2022-04-19 at 9 11 08 AM" src="https://user-images.githubusercontent.com/1610503/164048373-7ed3e067-0b78-450f-9928-82dfc3e75884.png">

### Environment

```markdown
Plausible.io website.
```

**Comment by RobertJoonas** [comment]
Hi @taylorlapeyre!

We get all the favicons from DuckDuckGo. By default, if an icon is not found for a given domain, DuckDuckGo responds with the default gray icon that you see for "google_ad" and "yahoo_native" in your screenshot. The "email" entry that you see in the Sources tab is an actual referrer website too and we use its referrer URL value to fetch the icon.

For some reason, DuckDuckGo responds with a 404 (instead of the default icon) for all domains starting with "email". For example:
- https://icons.duckduckgo.com/ip3/xxxx.xx.ico -> default icon
- https://icons.duckduckgo.com/ip3/email.xx.ico -> 404

I've just reached out to DuckDuckGo asking about this via email. Hopefully, they can get it fixed and as soon as they do, we will start displaying the default icon. Closing this as there's nothing we can do on our end to fix this.
