### ISSUE TITLE
Emails not sent using Postmark

### ISSUE THREAD

**Issue by grobmeier** [plausible/analytics#1895]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

According to the docs, the only settings necessary to use postmarkapp is to create an api key and change the adapter.

I added those fields to my plausible-conf.env

```
MAILER_ADAPTER=Bamboo.PostmarkAdapter
POSTMARK_API_KEY=<api key removed>
```

The instance was restarted after that. The server can reach the postmark server using HTTP (ports open etc).
Still, there was never a single email sent.

Are there any logfiles plausible writes where I could look for additional info? Or is there are problem with Postmark in general?

https://plausible.io/docs/self-hosting-configuration#mailersmtp-setup

### Expected behavior

Sends the email

### Environment

```markdown
- OS: 
- Browser:
- Browser Version:
```

**Comment by metmarkosaric** [comment]
thanks for the feedback @grobmeier! this is more of a support request rather than a bug. we keep this issues list to bugs only. self-hosted is community supported only. the best place for self-hosted support is to search or post your issue in the forum and hopefully a community member who's had the same problem can help you out: https://github.com/plausible/analytics/discussions/categories/self-hosted-support. thanks!

**Comment by grobmeier** [comment]
Why do you think this is not a bug?

**Comment by grobmeier** [comment]
Fixed with https://github.com/plausible/docs/pull/228
