### ISSUE TITLE
Only allow admin user to add new websites

### ISSUE THREAD

**Issue by tpimh** [plausible/analytics#1905]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

With publicly exposed self-hosting Plausible instances, where registration and login are not disabled, it's possible to register new user accounts, add any websites, and use the dashboard without any limits.

### Expected behavior

A solution to this can be as simple as adding a setting like `USERS_CAN_ADD_WEBSITES`. When this setting is set to `FALSE` (I suggest this should be the default), anyone can still register, but only the `ADMIN_USER` can add new websites (other users can be invited to become Admins or Viewers of these sites, but can never become Owners). In my opinion, this behavior will prevent the unwanted external users from exploiting the self-hosted installations.

### Environment

```markdown
- OS: any
- Browser: any
- Browser Version: any
```

**Comment by metmarkosaric** [comment]
Thanks for the feedback @tpimh! This is more of an idea for a way to improve Plausible rather than a bug report. We keep "issues" section to the actual bugs with the product only. Please do post your idea to [our forum](https://github.com/plausible/analytics/discussions) instead where we keep the list of feature requests and where it's easier for us to get an overview of all the ideas and prioritize the future development. Thanks!

**Comment by tpimh** [comment]
Hi @metmarkosaric! Thank you for your rapid reply! I have changed the wording a little, and reposted as a feature request #1906. You can close this issue if you think it's not an actual bug report.

**Comment by metmarkosaric** [comment]
thank you!
