### ISSUE TITLE
Support for nordic letters

### ISSUE THREAD

**Issue by Mathias-Syversen** [plausible/analytics#1916]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Letters like Æ Ø and Å is not supported in domain name, error: "only letters, numbers, slashes and period allowed".

### Expected behavior

I expected allowed domain letters to be supported by the service.

### Environment

```markdown
OS: MacOS
Browser: Chrome
Browser Version: 1.38.119
```

**Comment by metmarkosaric** [comment]
thanks for the feedback @Mathias-Syversen! there's already a thread for this feature request. see https://github.com/plausible/analytics/discussions/993

**Comment by Mathias-Syversen** [comment]
Ah, I did not see the discussion.

Anyways, this discussion is one year old, with no indications that it will be done.
I would still say this is a bug, not a feature request. Plausible does not support all characters supported by domain names, this diff makes it impossible for me to argue for plausible when setting up new projects.

If it is a valid domain, it should be valid in plausible too.
If you are just using regex validation for the domain input, updating it to support the additional characters should not be a time-consuming or difficult task?

**Comment by metmarkosaric** [comment]
no problem!

we don't typically respond to threads promising anything about when something will be done as we're a small team with limited resources. when the work starts on a feature or when we need some feedback, we post more info on the relevant thread. having duplicate threads for same ideas just makes it more complicated to plan and prioritize as we prioritize our development according to the popularity of a request.

for us a bug is a feature we support but that doesn't actually work. we've never supported special characters including nordic letters which is why it is more of a feature request for us. thanks for understanding!

**Comment by metmarkosaric** [comment]
as explained, closing this as there's already a thread for this request https://github.com/plausible/analytics/discussions/993
