### ISSUE TITLE
Tooltip sometimes says "Visitors" and other times "Converted Visitors" when filtering by goal

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#1926]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Tooltip sometimes says "Visitors" and other times "Converted Visitors" when filtering by goal. "Visitors" is displayed on today, last 30 days, last month and last 12 months

### Expected behavior

We should change it to say "Converted Visitors" in all cases when filtered by goal.

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by Vigasaurus** [comment]
Do you have any consistent reproduction for this? I too had seen something similar in testing where the unique conversions metric selection for the main graph wasn't happening automatically at times when filtering into a goal (which causes the tooltip to use the wrong header), but I haven't been able to reproduce it since.

**Comment by metmarkosaric** [comment]
yeah, it doesn't seem to be consistent. i can look at the one view and see "Visitors" but then try that same view again and it would say "Converted Visitors".
