### ISSUE TITLE
Main domain being tracked being tracked as sub-domain

### ISSUE THREAD

**Issue by ejaime-fundre** [plausible/analytics#1945]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Our main domain is **foo.domain.com** and we have testing environments like **foo.app.domain.com**, users accessing foo.app.domain.com are being tracked in foo.domain.com. 

We've searched through the docs and there might not be any way to also exclude some subdomain from being tracked. We're assuming that Plausible is tracking everything under **domain.com**. 

### Expected behavior

We expect plausible to track the exact domain that where specified even when the main domain is composed by multiple parts (Like ours foo.domain.com).

### Environment

```markdown
- OS:All
- Browser: All
- Browser Version: Latest
```

**Comment by metmarkosaric** [comment]
thanks for reaching out @ejaime-fundre! 

this is expected behavior as it's how Plausible works. other analytics tools like GA work in the same way too. if our script is installed on a page, it will send that visit to whatever property is listed under data-domain in the snippet no matter if that's not the actual URL of the site. 

if you don't want to track specific sections of your site, you can use our exclude script. see https://plausible.io/docs/excluding-pages

alternative is to exclude the visits of people you don't want to be tracked. see the instructions here: https://plausible.io/docs/excluding. you can exclude your visits by setting a localstorage flag in your browser too. see https://plausible.io/docs/excluding

**Comment by metmarkosaric** [comment]
closing this as explained above

**Comment by elias89** [comment]
Thanks for the quick response @metmarkosaric

**Comment by ejaime-fundre** [comment]
Thanks for the quick response @metmarkosaric
