### ISSUE TITLE
UX: Provide visual indicator of how to switch sites in Plausible.io 

### ISSUE THREAD

**Issue by danyork** [plausible/analytics#195]
Hi. In my free trial I've got Plausible connected to two sites. From within the https://plausible.io/ interface, it was not clear to me how to switch from analytics about one site to see the analytics for the other site. I eventually figured out that I needed to click on the Plausible logo in the upper left to get to my list of sites.

It would be great if there was some visual indicator of how to switch to another site.  My own preference would be for the domain name in the "Analytics for [domain name]" to be a drop-down allowing me to switch between sites:

<img width="297" alt="site-assumes-https" src="https://user-images.githubusercontent.com/41662/86038890-a5f82400-ba0f-11ea-8bc2-d32624bc7b52.png">

If I'm in your site looking at analytics, I would personally find it more useful to switch between sites rather than having the domain name take you over to the actual site.

If you want to retain the current behavior of the domain name taking you to the current site, then perhaps have something else up in the menu that says "Switch site" or something like that.

**Comment by metmarkosaric** [comment]
Thanks @danyork! As the short term fix we could add something like "Sites" to the top navigation to make it easier to understand and then the drop-down switch would be a nice improvement to the current implementation.

**Comment by danyork** [comment]
Sure, that works. Just having "Sites" up there on the menu would probably be fine.

**Comment by toothbrush** [comment]
I ran into this exact issue.  To clarify @metmarkosaric, i would vote for your solution of a dropdown to change sites, and i think it would _not_ be an improvement to have a link saying 'Sites' which would make me wait for a page load before being able to select the site i want (since by now i know to click the logo or simply select another property by URL from my browser history).  I think avoiding an extra page load is critical to making this user-friendly.

Thanks for your good work!  I'm currently on the free trial but it's 99% sure i'll be converting to paid soon.
