### ISSUE TITLE
Shadow are cut outside the iframe on the embed

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#1954]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

"I've been playing with embeding an iframe into a cms and shadow are cut outside the iframe which creates some nasty effect on some inputs and blocks"

### Expected behavior

"From what I can see (I'm a webdev), there a two ways to fix this problem :

* Adding a 25px (larger shadow offset) padding to the left and the right of the content. For exemple, adding the style "padding: 0px 25px;" on the body fixes the problem. Of course that should be done on embedded views only.

* Replacing shadow with borders on borders. That would of course change the style a little but since borders don't overflow, there would be no problem."

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by stevenart** [comment]
Hi.

Some more information (I reported the bug to @metmarkosaric):
- An example wan be found here : https://jsfiddle.net/hvzonamu/
- Screenshots attached.
- As far as I can tell, the "bug" is browser-agnostic and os-agnostic since it is really the "normal" behavior of an iframe.

![Screenshot from 2022-06-09 19-14-33](https://user-images.githubusercontent.com/3276322/173025998-4462cfef-78a8-4a62-9773-8a2faa687608.png)
![Screenshot from 2022-06-09 19-14-42](https://user-images.githubusercontent.com/3276322/173026006-319cf9b1-fad1-4d2b-a6b6-8161d1f3b8cb.png)
