### ISSUE TITLE
/stats/breakdown endpoint is not accurate when using a specific page path filter

### ISSUE THREAD

**Issue by jacoblatona** [plausible/analytics#2141]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

When performing a /stats/breakdown query for example, the pageviews returned from the query is like 8X the amount of actual pageviews. 

For example **/order/confirmation** has 8 total page views. This is accurately reported from the /stats/aggregate and /stats/timeseries endpoints. 

However, 

When I run this query for example for top browsers as a breakdown

`/stats/breakdown?site_id=plausible.io&filters=event:name==pageview;event:page==/order/confirmation&metrics=pageviews&property=visit:browser&limit=5`

This returns something to the effect of

Chrome: 45
Firefox: 20
Opera: 5

Which is way more pageviews than the 8 total is actually has. 

### Expected behavior

Return the accurate total number of page views for breakdown queries

### Screenshots

Here are actual screenshots from my app. 

This image is an aggregated query with the total page views for a particular path, for example /order/confirmation let's say. This data is correct and is working fine. 

![plausible-issue-1](https://user-images.githubusercontent.com/67568514/187053679-f645e4d6-7066-4933-9ea0-5a2fcc86028f.png)

This image is a /stats/breakdown query, for the top browsers/os's/countries

![plausible-issue-2](https://user-images.githubusercontent.com/67568514/187053710-011a9014-c982-46d2-b7d3-15af675d8cb2.png)

As you can see, the numbers are extremely inflated/wrong. 

Here is my actual query I am using that is returning the incorrect breakdown data with a few variables swapped for privacy and simplicity.

`
const topCountryData = await fetch(
      analyticsBaseUrl +
       "/stats/breakdown?site_id=plausible.io&filters=event:name==pageview;event:page==/order/confirmation&metrics=pageviews&property=visit:country&limit=5",
      {
        headers: {
          Authorization: Bearer ${apiKey},
        },
      }
    );
`

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by RobertJoonas** [comment]
This currently happens because when breaking down on a session property with `metrics=pageviews`, Plausible counts all pageviews from every session where at least one event matches with the criteria specified in the filters. So following your example, with these filters:

1. event:name==pageview
2. event:page==/order/confirmation

we'd first find all "converted sessions", and then count the number of pageviews between these sessions. This is the intended behavior. Would be nice to allow overriding this and count pageviews from converted sessions based on the event level filters too. Unfortunately I cannot make any promises on when we'll be able to work on this as we're a small team with limited development resources and need to take it one step at a time. Thanks for understanding!
