### ISSUE TITLE
IP Geo Location showing ISP HQ location

### ISSUE THREAD

**Issue by Why8046** [plausible/analytics#2166]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Geo locations shows not current location but the location of the ISP.

Visited chisca.com from my office in Chamblee GA from laptop and mobile phone.

Stats show:
Marietta GA for laptop (comcast)
New York City for mobile phone (Verizon)

This will become a problem when we do local marketing and cannot see real location of visitors.
![Screenshot_3](https://user-images.githubusercontent.com/112729984/188232325-f3554910-a778-49b5-9559-cb0dc6942bbc.jpg)

On another site, it shows me logged in 3 hours from where I actually am.

### Expected behavior

Stats should show exact location where I am when visiting the site.

### Screenshots

![Screenshot_3](https://user-images.githubusercontent.com/112729984/188232442-af3004b3-ee42-4b30-9ecb-9c348d681b0a.jpg)

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
- Browser Version: Version 104.0.5112.102 (Official Build) (64-bit)


- OS: Android
- Browser: DuckDuckGo 
- Browser Version:5.1300
```

**Comment by metmarkosaric** [comment]
Thanks for reporting that @Why8046!

We use the [DB-IP](https://db-ip.com/) database to look up the location of an IP address. Could you please test your IP addresses on their website to see what location they show?

We tested several geolocation database providers over several months and DB-IP was able to locate the most IP addresses in the most accurate way. Here's what they say on their website:

"We aggregate data from a large number of sources and through agreements with popular ISPs. We constantly evolve our machine learning models for more accurate IP address geolocation."

What we've noticed is that in situations where they don't have the exact match on the location, rather than not showing any location for that visitor they tend to look at the wider area. Other database providers we tested would simply not show any location in those cases so for us this was a better solution.

Unfortunately, when DB-IP gives us the wrong city for some IP address, there's nothing we can do on our end other than report it and hope that their database improves. We constantly get any improvements that they make so when they make updates, our geolocation accuracy improves too.

Sorry about that and thanks for understanding!

**Comment by metmarkosaric** [comment]
after some more testing of different geolocation databases, we have now gone live with a switch of the database provider. we now use the maxmind database instead. no database is 100% accurate unfortunately but this change should provide some more accuracy in terms of cities. details https://plausible.io/docs/countries#how-it-works
