### ISSUE TITLE
Data imported from Google Analytics disappears when applying any filter.

### ISSUE THREAD

**Issue by andyj2022** [plausible/analytics#2906]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Data imported from Google Analytics disappears when applying any filter. Data imported from Google Analytics disappears when applying any filter. All metrics go to zero.

### Expected behavior

That the data imported from Google Analytics is useful for something...

### Screenshots

BEFORE FILTER

![imagen](https://user-images.githubusercontent.com/102581305/236855276-0047e11e-9eff-45bd-a103-0ceaadfe4d01.png)

AFTER FILTER

![imagen](https://user-images.githubusercontent.com/102581305/236854758-2819f60f-d3ce-496b-a152-d44ae4969f97.png)

### Environment

```markdown
- OS: Windows 11
- Browser: Firefox
- Browser Version: Latest
```

**Comment by metmarkosaric** [comment]
Thanks for reporting @andyj2022! This is expected. We have taken many steps to make the imported data feel as fast, easy, and straightforward as the native data collected by Plausible directly. But it's important to note that imported data won't be as flexible as the native data that we collect using our script simply due to the fact that we get it from the Google API and that has limitations.

One of these limitations is that you cannot filter your dashboard and view any imported data. You can only view the imported data when the dashboard is not filtered. You can see [all the other differences here](https://plausible.io/docs/google-analytics-import#how-does-imported-data-differ-from-plausible-native-data).

**Comment by andyj2022** [comment]
Gracias, pero no lo entiendo. Si importan los datos y se pueden vers in filtros, ¿por qué no se pueden ver con filtros, si los datos realmente existen?

¿Hay alguna manera de convertir los datos de Analytics en datos normales?

Para mi organización son inútiles si no se pueden filtrar.

**Comment by metmarkosaric** [comment]
We have more technical details on this limitation in our docs: GA data is imported using Google's Reporting API v4 which has limits on the number of dimensions that can be fetched in a single query. This means we can't fetch entries that contain all the dimensions we are interested in and instead need to fetch data for each dimension individually. Unfortunately, this means we are unable to look at how dimensions interact which is why we cannot filter imported data in our dashboard.

**Comment by andyj2022** [comment]
The site I manage has 60 million pageviews per year, and is in more than 30 languages. If I can't filter by URL, the import from Google Analytics seems pretty useless to me.
