### ISSUE TITLE
Large drop in measured traffic, no change in other sources

### ISSUE THREAD

**Issue by nicbou** [plausible/analytics#3060]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Apologies if this is the wrong place to ask.

I see a traffic drop of roughly 15% for https://allaboutberlin.com, seemingly across all sources, pages, devices etc. It started about eight days ago. When I look into Google Search Console, I don't see any dip in traffic. Those are the only methods I use to measure traffic.

There are no matching changes on the website. I suspect two things:

1. I proxy plausible.io calls through my server, which is behind Cloudflare. Has the Plausible.io script changed recently?
2. My Plausible script is loaded as /whoisthere.js. It might have been added to a more mainstream blocklist. I don't see any recent mentions of it though.

Do you have any other ideas? That drop scared me for a few days, until I could see that the traffic was just fine using another source.

### Expected behavior

The traffic (from Google) measured by Plausible is proportional to what is tracked by Google Search Console

**Comment by metmarkosaric** [comment]
hi @nicbou! i can see that the `allaboutberlin.com/whoisthere.js` has been added to the Easyprivacy blocklist and that one is used by adblockers such as uBlock Origin so that probably explains it. try to change the name of the file.

and btw the best place for these types of questions in the future is [our customer support](https://plausible.io/contact). we keep GitHub issues for actual bugs with the product only. thanks!

**Comment by nicbou** [comment]
The script was already in this blocklist for a long time, but the discrepancy is new. That's why I was wondering if something changed.

I will contact customer support, thanks!
