### ISSUE TITLE
Region names are in Swedish language for Finland

### ISSUE THREAD

**Issue by jmp** [plausible/analytics#3260]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Region names for Finland are for some reason displayed in Swedish. For example:

* Södra Österbotten
* Norra Karelen
* Kajanaland
* Mellersta Finland
* Nyland

Region names for other countries seem to correctly use the English names when available.

See also the attached screenshot. See also the related ticket #1740 with a similar issue.

### Expected behavior

[English names](https://en.wikipedia.org/wiki/Regions_of_Finland#List_of_regions) for the regions of Finland should be used. For example:

* South Ostrobothnia
* North Karelia
* Kajaani
* Central Finland
* Uusimaa

### Screenshots

<img width="482" alt="image" src="https://github.com/plausible/analytics/assets/183207/936b3e23-642c-49fb-99cc-2fd4049dc206">

### Environment

```markdown
- OS: All
- Browser: All
- Browser Version: All
```

**Comment by Kylmakalle** [comment]
I've found the root cause. Three years ago, the `geonames.csv` scrapper was [improved](https://github.com/plausible/location/commit/d01be9f747677b511d98b4253de1422868867489#diff-d274a64fbdb8caac8c654952034a8323f15ae203e4105cc6b1616d7b877fea74L33-R35) to have Swedish translations for Swedish regions. The parser uses Swedish (sv) column as English.

Since Finland also has region names in Swedish in ISO, this affects scrapping for Finnish regions.

Perhaps, we need to Skip the Swedish parser for English (are Swedish names better than English, [like Estonian](https://github.com/plausible/location/blob/31f91c4df430cfc16219000ac667cc665826b77c/lib/scraper/scraper.ex#L5-L6)?)

```elixir
  @translations_dest Application.app_dir(:location, "/priv/iso_3166-2.en-translations.json")
  @countries_to_skip [
    "EE",  # For Estonia the local names are better than English ones
```

Adding more country-specific logic (e.g. using the `(fi)` column for `FI`) feels unnecessary.

@ukutaht what do you think? I may try to make a PR.

<img width="955" alt="image" src="https://github.com/plausible/analytics/assets/24507532/c64bb000-3e6f-4734-a608-a402cf997b0f">

**Comment by ukutaht** [comment]
Thanks @Kylmakalle ! I agree with your analysis and suggestions (mostly)

> Perhaps, we need to Skip the Swedish parser for English (are Swedish names better than English, [like Estonian](https://github.com/plausible/location/blob/31f91c4df430cfc16219000ac667cc665826b77c/lib/scraper/scraper.ex#L5-L6)?)

Yeah I wasn't sure about this - I am Estonian and I know that in Estonia everyone says *'Harjumaa'* not *'Harju'* to refer to the region. This is including non-Estonian speaking people.  It would be confusing to say *'Harju'* or *'Viru'* without the *'-maa'* suffix to refer to the region. I assumed that in Sweden it's similar - that the *-län* suffix is always used.

Finland seems different because the regions have completely different names in different languages. IMO we should prefer English in this case (for anyone outside of Finland, *Central Finland* is much better than *Keski-Suomi*).

I think the best course of action is to make a surgical change to the location scraper - make sure to only use the `sv` translation for Swedish regions. This would keep The swedish names the same but fix the Finnish region names. What do you think?

**Comment by Kylmakalle** [comment]
I've updated the parser to use Swedish names only for Sweden. Finland will have English names. @ukutaht please see https://github.com/plausible/location/pull/10

P.S. It does not make much sense for me to have Swedish translations for Sweden, taking into account that the names are extremely similar to their English representations. I don't know Swedish, so I can't judge the need for the _-län_ suffix. Considering the historical usage of Swedish names for Sweden and the lack of negative feedback about it, I'm leaving it as is.
