### ISSUE TITLE
Incorrect Content-Type for request?

### ISSUE THREAD

**Issue by dominic-p** [plausible/analytics#3390]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I noticed that the request being made to /api/event uses a Content-Type header of text/plain, but the body of the request is JSON. Is there a reason for this?

I know it's not a big deal, but it seems like the header should match the content. Also, ModSecurity with the Core Ruleset enabled blocks these requests by default due to the text/plain type being used.

### Expected behavior

I expected the Content-Type request header to be set to `application/json`

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
- Browser Version: NA
```

**Comment by ukutaht** [comment]
If my memory is right this is in order to avoid a CORS preflight request. If the content-type was `application/json`, the browser would make 2 roundtrips to the server. 

But I'm not sure if it's needed anymore since we added proper CORS headers: https://cors-test.codehappy.dev/?url=https%3A%2F%2Fplausible.io%2Fapi%2Fevent&origin=https%3A%2F%2Fcors-test.codehappy.dev%2F&method=post

**Comment by dominic-p** [comment]
That's interesting. I did a basic test and switched the content-type on my instance. Sure enough, I started getting a preflight request. It looks like the behavior is [documented here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests).

Given that, it probably makes sense to leave the current configuration alone unless you feel differently. Feel free to close this.

**Comment by ukutaht** [comment]
Thanks for double-checking!
