### ISSUE TITLE
Plausible geolocation doesn't match what IP databases report

### ISSUE THREAD

**Issue by bnelson-czi** [plausible/analytics#3728]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Geolocation doesn't show our current location when at our company office, similar to a previous issue (#2166). I wasn't sure which database Plausible was using, since this page says [MaxMind](https://plausible.io/docs/countries#how-it-works) and this one says [db-ip](https://plausible.io/docs/self-hosting-configuration#ip-geolocation). Maybe the docs are outdated or this is a cloud vs self-hosting difference? In any case, our in-office team tested IP addresses with both MaxMind and db-ip, both of which show results that don't match what we see in Plausible.

- Visited https://cryoetdataportal.czscience.com/ from the company office in Redwood City, CA.
- [MaxMind](https://www.maxmind.com/en/locate-my-ip-address) reports San Francisco and sometimes Redwood City.
- [db-ip](https://db-ip.com/) reports Redwood City.
- Plausible reports New York City.

Note that geolocation seems to be accurate when visiting the site outside the company network. Still, the difference between what these databases report vs what Plausible reports makes us wonder where the miscommunication is happening.

### Expected behavior

Plausible shows correct location when visiting the site from our company network or at least matches what MaxMind or db-ip reports.

### Environment

```markdown
- OS: Mac 
- Browser: Chrome, Firefox
- Browser Version: 120, 122
```

**Comment by metmarkosaric** [comment]
Thanks for reporting @bnelson-czi!

We use Maxmind for the location reports. The other link you found is not related to our cloud service.

I think the best would be to test the IP address in question on Maxmind website where they will give you what they think is the location of the IP address: https://www.maxmind.com/en/home

And if it shows the wrong location, you could report it to Maxmind. They're pretty good at fixing any reports. And if they fix it, it will also be fixed in Plausible. Here's where you can report a wrong location https://www.maxmind.com/en/geoip-data-correction-request

Feel free to contact our customer support directly and we can help with this https://plausible.io/contact

Thanks!

**Comment by bnelson-czi** [comment]
Hi Marco, thanks for the prompt reply. To clarify, we already did exactly what you recommended. MaxMind said our IP address location is SF/Redwood City, but Plausible said it's New York City. The problem is the mismatch between what MaxMind and Plausible claim. With that in mind, should we reopen the issue? Otherwise, I'll contact customer support. Thanks.

**Comment by metmarkosaric** [comment]
thanks for checking @bnelson-czi! that's weird as we use the Maxmind database ourselves and we update it weekly. and there's no VPN or similar thing on your network that prevents the real IP address from being sent to us? as it involves IP addresses, i think it's best to contact our support directly and share the full IP address so we can investigate. thanks!
