### ISSUE TITLE
Docker-based setup does not support custom event props

### ISSUE THREAD

**Issue by gurupras** [plausible/analytics#425]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
The version of Plausible present in the docker setup does not support custom event `props`

**Expected behavior**
Following the instructions in the docs should result in a container that has all the capabilities listed in the (rest of the) docs.

**Screenshots (If applicable)**
![image](https://user-images.githubusercontent.com/2933207/99487275-eeb76780-2933-11eb-9c2f-8055108174ce.png)
In the screenshot above (minified plausible.js code), `t.props` is never used.

**Environment (If applicable):**
 - OS: Ubuntu 18.04
 - Browser Chrome
 - Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by metmarkosaric** [comment]
Thanks! This is not a bug but expected behavior. We update Plausible Analytics Cloud pretty much daily with improvements and new features. These are then battle tested on thousands of sites using Plausible Analytics before we release them to the self-hosted analytics. Self-hosted analytics is not updated with new version releases so frequently. You can follow the latest updates and releases of self-hosted analytics here: https://github.com/plausible/analytics/releases
