### ISSUE TITLE
Site provisioning API returns 404

### ISSUE THREAD

**Issue by tiotdev** [plausible/analytics#4288]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

The post request
```
curl -X POST https://plausible.mydomain.com/api/v1/sites \
  -H "Authorization: Bearer ${TOKEN}" \
  -F 'domain="test-domain.com"' \
  -F 'timezone="Europe/London"'
```
returns 404 Not Found

This is from the docs: https://plausible.io/docs/sites-api

The Site provisioning API is not mentioned as not being included in the CE here https://plausible.io/self-hosted-web-analytics

I assume this is a bug.

### Expected behavior

I expect the API request to work

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by ruslandoga** [comment]
👋 @tiotdev 

Site provisioning API is indeed not included in CE: https://plausible.io/blog/community-edition#a-stronger-moat-for-our-official-managed-hosting

**Comment by mpas97** [comment]
@ruslandoga Wow, what a breaking change. We can't understand how can you delete such a feature "because users haven't noticed them". For us, the API was a central part as we provision adhoc websites (multiple hundreds) including an own dashboard that shows the plausible data. That we now have to register and delete every website on plausible manually as kubernetes resources come and go, is really not cool / managable. We (as a university) would be willing to pay, but we want to continue running it on our own kubernetes cluster. Is there any product/license for that?

**Comment by ruslandoga** [comment]
👋 @mpas97 

> Is there any product/license for that?

AFAIK there is no self-hosted "enterprise edition" nor license available right now. Sorry.

**Comment by mpas97** [comment]
Thanks, I will contact them now 🙏

**Comment by mpas97** [comment]
FYI: I got an answer "Unfortunately this is not something we can offer." 😢

**Comment by max-degterev** [comment]
This kind of defeats the purpose of self hosting entirely. Did anyone find a suitable replacement?

**Comment by max-degterev** [comment]
To answer my own question:
1. https://docs.swetrix.com/selfhosting/how-to
2. https://umami.is/docs/install

Goodbye Plausible, it's been fun ✋

**Comment by RyanCasas** [comment]
> FYI: I got an answer "Unfortunately this is not something we can offer." 😢

For the record, version 2.0.0 did include the Site Provisioning API. I had it integrated on one of our SaaS projects and upgrading to v2.1 broke it. Reverting back to 2.0.0 made it work again.
The non-self-hosted solution isn't an option due to the amount of API requests we use to display stats on a dashboard.
We will look into a replacement soon, as this is a dealbreaker.

**Comment by max-degterev** [comment]
Umami has been very good so far, no issues with deployment, performance OK
