### ISSUE TITLE
Region "IN-TS"

### ISSUE THREAD

**Issue by vstollen** [plausible/analytics#4375]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Today, I had a visitor vom Country: India, Region: IN-TS, City: Hyderabad.

### Expected behavior

Show the correct region name. Probably Telangana.

### Environment

```markdown
- OS: MacOS
- Browser: Arc
- Browser Version: 1.51.0
```

**Comment by ruslandoga** [comment]
👋 @vstollen 

This and some other region names should be fixed in https://github.com/plausible/analytics/pull/4366

Compare:
- Now: https://plausible.io/plausible.io/regions?filters=((is,region,(IN-TS)))
- IN that PR: https://pr-4366.review.plausible.io/plausible.io/regions?filters=((is,region,(IN-TS)))
