### ISSUE TITLE
Event API does not work from val.town.

### ISSUE THREAD

**Issue by RLesser** [plausible/analytics#4768]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I tried to call the event api from https://www.val.town/, and it got blocked with the `x-plausible-dropped`. I assume this is because val.town requests come from a data center of some sort. Is there any way to get val.town off of whatever blocklist is causing this? In the meantime I plan to run the requests from the client, but would like to move it server-side if I can.

### Expected behavior

Request goes through successfully.

### Environment

```markdown
- OS: MacOS
- Browser: Arc
- Browser Version:
```

**Comment by metmarkosaric** [comment]
Thanks for reaching out @RLesser! 

The message you're seeing about the event being dropped is likely due to you not sending the IP address of your actual visitor to us. This would make our system think it's a bot and would drop it.

You would need to send the actual user agent and IP address of the visitor. You can the instructions here https://plausible.io/docs/events-api 

I'll close this as we keep the issues list to bugs with the product only. Better place for support and questions about the product is our customer support. See https://plausible.io/contact
