### ISSUE TITLE
Referral Data shows 'no data yet'

### ISSUE THREAD

**Issue by bdickason** [plausible/analytics#498]
I have a small blog and have a use case that I think Plausible should serve well: For visitors who sign up for my newsletter, tell me where they came from (twitter, facebook, etc) and what page they landed on.

Currently, all the data is populated properly (e.g. my event for signing up) but the 'Top Sources' box is blank and says 'no data yet.'

**Comment by metmarkosaric** [comment]
thanks @bdickason! could you share more details please as it's really difficult to troubleshoot from the info you provided. The URL of the website? Which referral sources you're looking at (Top Sources on the default dashboard or when filtered by a particular goal)? Screenshots from the dashboard? thanks!

**Comment by bdickason** [comment]
Oops sorry @metmarkosaric I should have thought of that.

Here you go:
**URL:** http://bdickason.com/
**Referral Soures:** I am looking at the 'Top Sources' on the default dashboard
**Screenshots**
<img width="1125" alt="Screen Shot 2020-12-22 at 8 56 55 AM" src="https://user-images.githubusercontent.com/202162/102913591-d3a8ad80-4433-11eb-8d0b-7978d4fcb8c4.png">
<img width="542" alt="Screen Shot 2020-12-22 at 8 56 46 AM" src="https://user-images.githubusercontent.com/202162/102913600-d6a39e00-4433-11eb-87f6-0a8f196dc315.png">

Let me know if you need more info!

**Comment by metmarkosaric** [comment]
Thanks for sharing the details! I understand now. 

The "Source" tab in the Top Sources report is for UTM_source tags. Did you include any UTM tagged links in your social media and so on? "Medium", "Source" and "Campaign" tabs is where any clicks on those links will show up. If you haven't had any clicks on the UTM tagged links, these reports would be empty. You can read more about tagging links here: https://plausible.io/docs/manual-link-tagging

It's the "All" tab on the Top Sources report that you are looking for in order to see all the normal referral sources that are sent using the referrer header. These are independent of the UTM tags.

**Comment by bdickason** [comment]
Thanks @metmarkosaric! I understand on medium/source/campaign now. I assumed Source was the traffic source e.g. the base website/app.

Appreciate it! I'll look into UTM tagged links from now on as well.

**Comment by metmarkosaric** [comment]
You're welcome! This blog post that we published recently is a good introduction to UTM tags and best practices when using them: https://plausible.io/blog/utm-tracking-tags
