### ISSUE TITLE
RFC: Adding more detail on maps

### ISSUE THREAD

**Issue by supersimple** [plausible/analytics#599]
On the map view of visitors, I noticed there is a list modal in world view. But when a country is selected, that modal just shows that one country.
The geo database plausible uses has more detailed information. Ideally, I would like to click on a nation and see that modal with a list of subdivisions enumerated. Of course, it may be a product decision to not get too detailed so I wanted to request a comment before submitting a PR.
WDYT?
![plausible](https://user-images.githubusercontent.com/773380/104547890-d8085680-55ec-11eb-83b6-a0ceb1866ede.gif)

**Comment by metmarkosaric** [comment]
thanks @supersimple! what do you mean by a "list of subdivisions enumerated"? right now we don't go any more granular other than country but there's a request to add states / regions / cities too. we'd like to do that but haven't got to it yet so any help is appreciated. Best place to discuss this is in the discussion forum rather than in issues which we keep to actual bugs only. See https://github.com/plausible/analytics/discussions/102 and https://github.com/plausible/analytics/discussions/219
