### ISSUE TITLE
Disable subscription pipeline when selfhosting

### ISSUE THREAD

**Issue by RealOrangeOne** [plausible/analytics#87]
It'd be great to disable the subscription workflow entirely when running self hosted. A 100 year free trial is definitely a quick way of implementing (and so generous :wink:), but it'd be nice if it were removed.

Specifically, the trial box on the top right, the "Subscription Plan" box in settings, and any integration with upstream payment.

**Comment by tckb** [comment]
that might require over-haul changes on the structure. It could be a milestone for **stable** release. :)

**Comment by ukutaht** [comment]
Yes, I think this requires a fundamental change to the backend. Currently a lot of the code assumes a trial flow for users.

To fix this properly, I think the analytics tool should not assume a business/subscription/payment model at all. It should only care about sites, users, events, sessions, etc. It should have a generic **admin API** that allows an admin to manage sites and users.

Then we could have another service like `billing.plausible.io` which manages the trial, sends billing emails, sends usage alerts and generally deals with things that are specific to Plausible *as a business* rather than Plausible *as an analytics tool*.

An admin API would open up new and interesting use-cases for self-hosting as well. People could embed Plausible in their own tools as an addon to re-sell it. I think @writeas would be interested in something like this and there have been other requests by website builders, hosting companies, etc.

Is this feasible for the first stable release? I'm not sure, it's a pretty big job and hard to justify at the moment. My nr. 1 priority is to be able to pay my own and Marko's salary so we can keep working on Plausible. This feature doesn't really help that goal in the short term.

If someone were to sponsor development for it, I can see us doing it in lieu of focusing on our core cloud offering.

**Comment by tckb** [comment]
>Is this feasible for the first stable release? I'm not sure, it's a pretty big job and hard to justify at the moment. 

fair enough.   

>People could embed Plausible in their own tools as an addon to re-sell it.

I totally see this as a valid option, that is why https://github.com/plausible/analytics/issues/88 would not be a good idea. Of course, I am working on some more _cosmetic_ changes for self-hosting.

**Comment by ukutaht** [comment]
Closed in #209
