### ISSUE TITLE
PDF redirects in Gatsby are not being tracked

### ISSUE THREAD

**Issue by flaviamuntean** [plausible/analytics#876]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
We've got a Gatsby site with several redirects which lead to a PDF. For example, if you go to `/privacy-policy` you are redirected to `/policies/Privacy_Policy.pdf`. The integration with Plausible was done using the [script](https://plausible.io/docs/plausible-script).

**Describe the bug**
It would appear that all of our usual pages, including redirects that lead to a regular page (i.e. `/team` redirects to `/careers`) are being tracked as expected and appear in the Plausible dashboard. However, redirects that lead to a .pdf page do not appear in the dashboard. This is something that used to work when using Google Analytics.

**Expected behavior**
I would expect to see `/policies/Privacy_Policy.pdf` listed in the Plausible dashboard.

**Comment by metmarkosaric** [comment]
thanks @flaviamuntean! moving this over to the forum as this is more of a feature request rather than an issue. as long as you don't have our tracking script embedded on a specific page, we cannot track it which means PDFs are not tracked. 

we could for instance track file downloads in the future which should cover this use case. at the moment, you could use our custom events to track clicks that lead to the PDF file
