### ISSUE TITLE
Timezone list doesn't follow the time change

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#904]
"The UK is currently on BST" which is GMT+1. CET is now GMT+2 etc while our static timezone list still has the previous time. Like I mentioned on Twitter, this doesn't affect the data/charts but is more cosmetic that should be fixed.

![ExwiM9qWQAEbfAL](https://user-images.githubusercontent.com/34340819/113100294-7fb02080-91fb-11eb-9df4-0803a594ed8a.png)

([feedback via twitter](https://twitter.com/ChildishGiant/status/1377013495909203968))

**Comment by ukutaht** [comment]
I see a lot of problems with following daylight savings automatically as well. Different countries have different rules about it. We don't collect information about which country the user is in, just the GMT offset. We know that someone is GMT+00 for example but there are many countries in that offset that follow daylight savings and many that don't.

🤦‍♂️ Let's just abolish daylight savings already. There's talk about it in the EU and other countries that follow it.

**Comment by ukutaht** [comment]
Ah darn this is a bit worse than I thought. Two separate issues:

1. All of our timezones are configured so that they do automatically follow the daylight savings rules _except_ for the one named 'Greenwhich Mean Time' which does not shift to GMT+1 during the summer.

2. And also the cosmetic issues are real. We're currently showing most timezone offset wrong because the local time is offset by 1 hour during the summer.

For 1. the fix is easy. I'll change in the backend from `Etc/Greenwhich` timezone to `Europe/London` so that it accounts for daylight savings.

For 2, I'm not sure what the clearest way to show offsets (accounting for daylight savings) is. For GB users, do we just show GMT+01 during summer and GMT+00 during winter?

**Comment by metmarkosaric** [comment]
Ahh I see! We could use BST or GMT+1 in the summer and GMT in the winter

**Comment by metmarkosaric** [comment]
for anyone encountering the GMT+0 bug during the summer time, it gets fixed by [switching your site timezone](https://plausible.io/docs/general) to this one:

![54xtXriF png small](https://user-images.githubusercontent.com/34340819/131491228-92bc5f3f-b47d-4b3e-94f9-e0660fe04662.png)

**Comment by masteradhoc** [comment]
> And also there's a third related issue: we're currently reccommending the wrong timezone to people. Here's what I get:
> 
> ![Screenshot from 2021-03-31 17-00-40@2x](https://user-images.githubusercontent.com/3731516/113156504-ba897700-9242-11eb-8b85-d5d93a4727d6.png)
> 
> Moscow is the wrong timezone for me. I should get `Europe/Helsinki` instead. So the recommendations are off by one as well.

Same Problem here. Get GMT+2 but should get GMT+1

**Comment by metmarkosaric** [comment]
“Just a heads up that the dashboard seems to be running in EST instead of EDT. Here’s a snapshot of mine at about 11:30 pm EDT on 3/16. It already has data for the early minutes of 3/17“

[Via Twitter](https://twitter.com/Hoffm/status/1504298971967242241?t=PoOTEs71T5D6Aq3I1xQ8gQ&s=19)

**Comment by MarcusOtter** [comment]
I am getting the correct timezone recommended to me (GMT+2), but the city label is wrong. It says Stockholm is in GMT +1 but we are in GMT +2. Was a bit confusing whether I should pick the correct timezone (GMT +2) or the correct city (Stockholm) since I know that Helsinki that is listed on GMT +2 is in GMT +3.
