### ISSUE TITLE
Custom domain for public dashboard

### ISSUE THREAD

**Issue by kasbah** [plausible/analytics#92]
Would be nice if we could serve up our public dashboard on our own sub-domain without having to self-host it.

**Comment by metmarkosaric** [comment]
Adding more info from [the old roadmap](https://plausible.nolt.io/79):

"It would be cool if publicly available stats was accessible on the custom domain. So that https://plausible.io/example.com could be accessed with e.g. https://stats.example.com. The custom domain root currently returns a 404.

This would be awesome for private stats as well."

**Comment by cassidyjames** [comment]
Came here to ask for exactly this, but the multi-site case makes it a little more complex. We heavily use Plausible at elementary and I have been thinking about setting up some sort of dashboard to make it easier for folks to find all of our stats pages, basically what I can see when logged into our account and on our dashboard. So a domain would need to be associated with an org/account, not just a site. And then it could show all of the public sites for that org.

**Comment by ruurtjan** [comment]
Jep, same here! I wouldn't mind hosting the javascript on a different custom domain as the dashboard though, if that makes it easier to incorporate @cassidyjames's additional request.
