### ISSUE TITLE
Filtering for 2 different custom props in API

### ISSUE THREAD

**Issue by rbange** [plausible/analytics#929]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help, support or feature requests. 

[Our docs](https://plausible.io/docs) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). 

Have a feature request? Please search the ideas [on our forum](https://github.com/plausible/analytics/discussions/categories/feature-requests) to make sure that the feature has not yet been requested. If you cannot find what you had in mind, please [submit your feature request here](https://github.com/plausible/analytics/discussions/new). 

Have an issue with your self-hosted install? You can ask in [our self-hosted forum](https://github.com/plausible/analytics/discussions/categories/self-hosted-support). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
When using the new API, filtering for 2 items separate custom props results in an error.
I would like to filter for 2 custom properties within a time series request like this:
`https://plausible.io/api/v1/stats/timeseries?site_id=SITE_ID&period=6mo&filters=event:name==GOAL_NAME;event:props:custom1==a;event:props:custom2==b`

```
{
  "error": "** (Ecto.Query.CompileError) alias `:meta` already exists"
}
```

**Expected behavior**
Summed up visitor counts (default metric) for both props 

**Screenshots (If applicable)**

**Environment (If applicable):**
not applicable / curl

**Comment by ukutaht** [comment]
Hi, thanks for reporting. This is a known limitation, I'll make a note in the docs. More information below about a slightly different issue but the cause is the same.

Copying my answer from [this thread](https://github.com/plausible/analytics/discussions/913)

> Unfortunately there is a limitation with the Clickhouse Nested datastructure that prevents us from doing a breakdown by one property while filtering on another. Sorry, this should be explained in the documentation.
> Clickhouse is working on a Map data type that will probably work better for custom props and will allow us to fix this problem. It's still unstable though so it will take some time until it's thoroughly tested and ready to be used.
> Sorry I don't have a better answer :/

I'm happy to keep this issue open until it's resolved. I agree that it feels like a bug, unfortunately there's nothing we can do at this point as we're constrained by the database.

**Comment by metmarkosaric** [comment]
thanks! this is more of a feature request rather than a bug. we keep this list to actual bugs in the product only. all the feature requests go to our forum where it's easier to keep track of them and it's then easier for us to consider them for prioritization in the future roadmap. there's already a thread on this idea with several comments both to introduce the [filtering by custom properties in the dashboard](https://github.com/plausible/analytics/discussions/846) and in the [api too](https://github.com/plausible/analytics/discussions/913).
